/* Generated By:JavaCC: Do not edit this line. AnalizadorConstants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AnalizadorConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMA = 1;
  /** RegularExpression Id. */
  int PUNTO = 2;
  /** RegularExpression Id. */
  int NEGATIVO = 3;
  /** RegularExpression Id. */
  int DOS_PUNTOS = 4;
  /** RegularExpression Id. */
  int SALTO = 5;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 6;
  /** RegularExpression Id. */
  int NOMBRE = 7;
  /** RegularExpression Id. */
  int NUMFILAS_VALOR = 8;
  /** RegularExpression Id. */
  int FECHA = 9;
  /** RegularExpression Id. */
  int VALOR_HORA = 10;
  /** RegularExpression Id. */
  int RECID = 11;
  /** RegularExpression Id. */
  int LATITUD = 12;
  /** RegularExpression Id. */
  int LONGITUD = 13;
  /** RegularExpression Id. */
  int VALOR = 14;
  /** RegularExpression Id. */
  int NUM = 15;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\",\"",
    "\".\"",
    "\"-\"",
    "\":\"",
    "\"\\n\"",
    "<IDENTIFICADOR>",
    "<NOMBRE>",
    "<NUMFILAS_VALOR>",
    "<FECHA>",
    "<VALOR_HORA>",
    "<RECID>",
    "<LATITUD>",
    "<LONGITUD>",
    "<VALOR>",
    "<NUM>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
  };

}
