/* Generated By:JavaCC: Do not edit this line. AnalizadorConstants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AnalizadorConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMA = 1;
  /** RegularExpression Id. */
  int PUNTO = 2;
  /** RegularExpression Id. */
  int NEGATIVO = 3;
  /** RegularExpression Id. */
  int DOS_PUNTOS = 4;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 5;
  /** RegularExpression Id. */
  int RECID = 6;
  /** RegularExpression Id. */
  int ESTADOSISTEMA = 7;
  /** RegularExpression Id. */
  int NOMBRE = 8;
  /** RegularExpression Id. */
  int NUMFILAS = 9;
  /** RegularExpression Id. */
  int LATITUD = 10;
  /** RegularExpression Id. */
  int NUM = 11;
  /** RegularExpression Id. */
  int HORA = 12;
  /** RegularExpression Id. */
  int MINUTO = 13;
  /** RegularExpression Id. */
  int HORARIO = 14;
  /** RegularExpression Id. */
  int DIA = 15;
  /** RegularExpression Id. */
  int MES = 16;
  /** RegularExpression Id. */
  int ANIO = 17;
  /** RegularExpression Id. */
  int FECHA = 18;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\",\"",
    "\".\"",
    "\"-\"",
    "\":\"",
    "<IDENTIFICADOR>",
    "<RECID>",
    "<ESTADOSISTEMA>",
    "<NOMBRE>",
    "<NUMFILAS>",
    "<LATITUD>",
    "<NUM>",
    "<HORA>",
    "<MINUTO>",
    "<HORARIO>",
    "<DIA>",
    "<MES>",
    "<ANIO>",
    "<FECHA>",
    "\" \"",
    "\"\\r\"",
    "\"\\n\"",
    "\"\\t\"",
  };

}
